In [3]:
import numpy as np

prices = np.array([199, 299, 399, 499, 599])

print("First Price:", prices[0])
print("Last Price:", prices[-1])

First Price: 199
Last Price: 599


In [2]:
scores = np.array([
    [50, 70, 80, 90, 60],
    [40, 60, 75, 85, 95],
    [30, 55, 65, 70, 80]
])

result = scores[:, 1:4]

print(result)

[[70 80 90]
 [60 75 85]
 [55 65 70]]


In [ ]:
ratings = np.array([4.5, 3.8, 4.2, 2.9, 5.0, 3.5])

last_three = ratings[-3:]

print(last_three)

[2.9 5.  3.5]


In [ ]:
numbers = np.arange(1, 21)

result = numbers[1::3]

print(result)

In [4]:
prices = np.array([299, 599, 450, 799, 999, 350, 650])

result = prices[prices > 500]

print(result)

[599 799 999 650]


In [5]:
scores = np.array([210, 180, 195, 220, 205, 175])

indices = np.where(scores > 200)

print(indices[0])

[0 3 4]
