In [ ]:
import numpy as np

zomato = np.array([4.5, 3.8, 4.2, 4.7, 3.9])
swiggy = np.array([4.1, 4.6, 3.7, 4.3, 4.8])

ratings = np.concatenate((zomato, swiggy))

print(ratings)

In [3]:
post1 = np.array([100, 120, 150, 180, 200, 220, 250])
post2 = np.array([90, 110, 140, 160, 190, 210, 230])
post3 = np.array([80, 100, 130, 170, 180, 200, 240])

stacked = np.vstack((post1, post2, post3))

print(stacked)

[[100 120 150 180 200 220 250]
 [ 90 110 140 160 190 210 230]
 [ 80 100 130 170 180 200 240]]


In [ ]:
product_ids = np.array([101, 102, 103, 104, 105, 106,
                        107, 108, 109, 110, 111, 112])

parts = np.array_split(product_ids, 5)

for part in parts:
    print(part, "Shape:", part.shape)

In [5]:
messages = np.array([
    [10, 20, 15, 25, 30, 20, 10],
    [5, 10, 8, 12, 15, 10, 5],
    [20, 25, 30, 20, 35, 40, 25]
])

new_user = [15, 20, 10, 25, 20, 15, 30]
messages = np.insert(messages, 3, new_user, axis=0)

print("After Insert:")
print(messages)

total_messages = np.sum(messages, axis=1)
least_user = np.argmin(total_messages)

messages = np.delete(messages, least_user, axis=0)

print("\nAfter Delete:")
print(messages)

After Insert:
[[10 20 15 25 30 20 10]
 [ 5 10  8 12 15 10  5]
 [20 25 30 20 35 40 25]
 [15 20 10 25 20 15 30]]

After Delete:
[[10 20 15 25 30 20 10]
 [20 25 30 20 35 40 25]
 [15 20 10 25 20 15 30]]


In [6]:
import numpy as np

views = np.array([1000, 2000, 3000, 4000, 5000])

view_data = views.view()
view_data[0] = 1500

print("Original after View:", views)
print("View:", view_data)

copy_data = views.copy()
copy_data[0] = 9999

print("Original after Copy:", views)
print("Copy:", copy_data)

Original after View: [1500 2000 3000 4000 5000]
View: [1500 2000 3000 4000 5000]
Original after Copy: [1500 2000 3000 4000 5000]
Copy: [9999 2000 3000 4000 5000]
