In [1]:
import numpy as np

ratings = np.array([4, 5, 3, 4, 2, 5, 4, 3, 5, 4, 2, 3, 5, 4, 1])

# Convert 1D to 3x5
ratings_2d = ratings.reshape(3, 5)

print("3x5 Array:")
print(ratings_2d)

ratings_1d = ratings_2d.flatten()

print("1D Array:")
print(ratings_1d)

3x5 Array:
[[4 5 3 4 2]
 [5 4 3 5 4]
 [2 3 5 4 1]]
1D Array:
[4 5 3 4 2 5 4 3 5 4 2 3 5 4 1]


In [3]:
prices = np.array([200, 350, 150, 500, 250])
discounts = np.array([20, 50, 10, 100, 30])

final_prices = prices - discounts

print("Final Prices:", final_prices)

Final Prices: [180 300 140 400 220]


In [4]:
scores = np.array([175, 190, 160, 210, 185])

result = scores > 180

print(result)

[False  True False  True  True]


In [5]:
paytm = np.array([1, 0, 1, 0, 0, 1])
phonepe = np.array([0, 1, 0, 0, 1, 1])

result = np.logical_or(paytm, phonepe)

print(result)

[ True  True  True False  True  True]


In [6]:
import numpy as np

steps = np.array([5000, 6500, 7000, 4500, 8000, 7500, 6000])

bonus_steps = steps + 500

total_steps = np.sum(bonus_steps)

print("Steps after bonus:", bonus_steps)
print("Total steps:", total_steps)

Steps after bonus: [5500 7000 7500 5000 8500 8000 6500]
Total steps: 48000
