In [1]:
import numpy as np

likes = np.array([120, 250, 180, 300, 450, 200, 500])

print("ndim:", likes.ndim)
print("shape:", likes.shape)
print("size:", likes.size)
print("dtype:", likes.dtype)
print("itemsize:", likes.itemsize)
print("nbytes:", likes.nbytes)

ndim: 1
shape: (7,)
size: 7
dtype: int64
itemsize: 8
nbytes: 56


In [ ]:

steps = np.array([
    [3000, 4000],
    [2500, 3500],
    [4000, 5000],
    [3200, 4200],
    [4500, 5500]
])


one_d = steps.reshape(10)

print(one_d)
print("Shape:", one_d.shape)


two_d = one_d.reshape(5, 2)

print(two_d)
print("Shape:", two_d.shape)

[3000 4000 2500 3500 4000 5000 3200 4200 4500 5500]
Shape: (10,)
[[3000 4000]
 [2500 3500]
 [4000 5000]
 [3200 4200]
 [4500 5500]]
Shape: (5, 2)


In [5]:
prices = np.array([
    [100, 200, 150, 250],
    [300, 120, 180, 220],
    [140, 160, 280, 350]
])

print("Original:")
print(prices)


ravel_data = prices.ravel()
print("Ravel:")
print(ravel_data)


flatten_data = prices.flatten()
print("Flatten:")
print(flatten_data)


resize_data = np.resize(prices, (6, 2))
print("Resize:")
print(resize_data)

Original:
[[100 200 150 250]
 [300 120 180 220]
 [140 160 280 350]]
Ravel:
[100 200 150 250 300 120 180 220 140 160 280 350]
Flatten:
[100 200 150 250 300 120 180 220 140 160 280 350]
Resize:
[[100 200]
 [150 250]
 [300 120]
 [180 220]
 [140 160]
 [280 350]]


In [ ]:
playlist = np.array([
    [10, 20, 30],
    [15, 25, 35],
    [12, 22, 32]
])

print("Original:")
print(playlist)


print("Using T:")
print(playlist.T)

print("Using transpose:")
print(np.transpose(playlist))

Original:
[[10 20 30]
 [15 25 35]
 [12 22 32]]
Using T:
[[10 15 12]
 [20 25 22]
 [30 35 32]]
Using transpose:
[[10 15 12]
 [20 25 22]
 [30 35 32]]


In [7]:
ratings = np.array([4, 5, 3, 4, 2, 5, 4, 3, 5, 4, 2, 3, 5, 4, 1])

ratings_2d = ratings.reshape(3, 5)

print("3x5 Array:")
print(ratings_2d)


ratings_1d = ratings_2d.flatten()

print("1D Array:")
print(ratings_1d)

3x5 Array:
[[4 5 3 4 2]
 [5 4 3 5 4]
 [2 3 5 4 1]]
1D Array:
[4 5 3 4 2 5 4 3 5 4 2 3 5 4 1]
