In [2]:
import numpy as np

my_scores = np.array([4, 5, 3, 4, 5])

print(my_scores)

[4 5 3 4 5]


In [ ]:


even_numbers = np.arange(10, 31, 2)

print(even_numbers)

[10 12 14 16 18 20 22 24 26 28 30]


In [ ]:


values = np.linspace(0, 1, 8)

print(values)

[0.         0.14285714 0.28571429 0.42857143 0.57142857 0.71428571
 0.85714286 1.        ]


In [4]:


cart = np.zeros(10, dtype=int)

cart[2] = 1
cart[6] = 1

print(cart)

[0 0 1 0 0 0 1 0 0 0]


In [5]:

np.random.seed(42)

otp_codes = np.random.randint(1000, 10000, 6)

print(otp_codes)

[8270 1860 6390 6191 6734 7265]
